# Generated by Django 2.1.7 on 2019-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('creation_date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('creation_date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.ForeignKey(on_delete=None, to='logo.Category')),
            ],
        ),
        migrations.CreateModel(
            name='LogoFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=16)),
                ('image_url', models.CharField(max_length=64)),
                ('logo', models.ForeignKey(on_delete=None, to='logo.Logo')),
            ],
        ),
        migrations.CreateModel(
            name='LogoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('logo', models.ForeignKey(on_delete=None, to='logo.Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('creation_date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('logo', models.ForeignKey(on_delete=None, to='logo.Logo')),
            ],
        ),
        migrations.AddField(
            model_name='logotag',
            name='tag',
            field=models.ForeignKey(on_delete=None, to='logo.Tag'),
        ),
    ]
