# Generated by Django 2.1.7 on 2019-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='logo',
        ),
        migrations.AlterField(
            model_name='logoformat',
            name='logo',
            field=models.ForeignKey(on_delete=None, related_name='formats', to='logo.Logo'),
        ),
        migrations.AlterField(
            model_name='logotag',
            name='logo',
            field=models.ForeignKey(on_delete=None, related_name='logotags', to='logo.Logo'),
        ),
    ]
