# Generated by Django 2.1.7 on 2019-05-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0002_auto_20190529_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='tags',
            field=models.ManyToManyField(through='logo.LogoTag', to='logo.Tag'),
        ),
    ]
